- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.PUBLISHQGISMEXICO_TOKEN }}
    external_repository: qgismexico/qgismexico.github.io
    publish_branch: master
    publish_dir: ./
